In [75]:
# let get down to cleaning part of the dataframes

In [76]:
import pandas as pd

In [77]:
from datasets import load_dataset

In [78]:
# now lets define the dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [80]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [81]:
# now we want to change type of job posted date to date and time (pd.to_datetime)
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [82]:
# suppose we want only date format (dt.date)
df['job_posted_date'] = df['job_posted_date'].dt.date
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [83]:
# First, let's restore df since it became None
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date']).dt.date

# Now we sort it correctly using inplace=True without assigning it back to df
df.sort_values(by='job_posted_date', inplace=True)

# Check the result
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
461362,Data Scientist,Turing Hiring Near Me – Remote Data Scientist ...,"Palo Alto, CA",via Jobs Picks,Full-time,False,"California, United States",2023-01-01,False,False,United States,None,NaN,NaN,Turing,"['python', 'tensorflow', 'keras', 'pandas', 'n...","{'libraries': ['tensorflow', 'keras', 'pandas'..."
274144,Data Scientist,STAGE - Assistant(e) Data Scientist – Quantum ...,"Montrouge, France",via BeBee,Internship,False,France,2023-01-01,False,False,France,None,NaN,NaN,Crédit Agricole S.A.,None,None
364349,Data Analyst,Functional analyst Adobe Analytics,"Madrid, Spain",via Recruit.net,Full-time,False,Spain,2023-01-01,False,False,Spain,None,NaN,NaN,Krell Consulting & Training,"['html', 'css', 'javascript', 'sql']","{'programming': ['html', 'css', 'javascript', ..."
364347,Senior Data Engineer,Senior Data Engineer (Innovation Insurer),Hong Kong,via Jobs In Hong Kong,Full-time,False,Hong Kong,2023-01-01,False,False,Hong Kong,None,NaN,NaN,MatchTalent Limited,"['sql', 'mongodb', 'mongodb', 'r', 'python', '...","{'analyst_tools': ['alteryx', 'tableau', 'qlik..."
346928,Cloud Engineer,"Data Center Storage with Avamar/Sacramento, CA...","Sacramento, CA",via LinkedIn,Contractor,False,"California, United States",2023-01-01,True,False,United States,None,NaN,NaN,Suncap Technology,None,None

In [84]:
# Ensure the column is a datetime type first to use the .dt accessor
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# Extract the month number (1 for Jan, 12 for Dec)
df['month_number'] = df['job_posted_date'].dt.month

# Display the change
df[['job_posted_date', 'month_number']].head()

       job_posted_date  month_number
461362      2023-01-01             1
274144      2023-01-01             1
364349      2023-01-01             1
364347      2023-01-01             1
346928      2023-01-01             1

In [85]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
461362,Data Scientist,Turing Hiring Near Me – Remote Data Scientist ...,"Palo Alto, CA",via Jobs Picks,Full-time,False,"California, United States",2023-01-01,False,False,United States,None,NaN,NaN,Turing,"['python', 'tensorflow', 'keras', 'pandas', 'n...","{'libraries': ['tensorflow', 'keras', 'pandas'...",1
274144,Data Scientist,STAGE - Assistant(e) Data Scientist – Quantum ...,"Montrouge, France",via BeBee,Internship,False,France,2023-01-01,False,False,France,None,NaN,NaN,Crédit Agricole S.A.,None,None,1
364349,Data Analyst,Functional analyst Adobe Analytics,"Madrid, Spain",via Recruit.net,Full-time,False,Spain,2023-01-01,False,False,Spain,None,NaN,NaN,Krell Consulting & Training,"['html', 'css', 'javascript', 'sql']","{'programming': ['html', 'css', 'javascript', ...",1
364347,Senior Data Engineer,Senior Data Engineer (Innovation Insurer),Hong Kong,via Jobs In Hong Kong,Full-time,False,Hong Kong,2023-01-01,False,False,Hong Kong,None,NaN,NaN,MatchTalent Limited,"['sql', 'mongodb', 'mongodb', 'r', 'python', '...","{'analyst_tools': ['alteryx', 'tableau', 'qlik...",1
346928,Cloud Engineer,"Data Center Storage with Avamar/Sacramento, CA...","Sacramento, CA",via LinkedIn,Contractor,False,"California, United States",2023-01-01,True,False,United States,None,NaN,NaN,Suncap Technology,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61924,Machine Learning Engineer,Senior/Staff MLOps Engineer,"Denver, CO",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,EvenUp,"['elasticsearch', 'bigquery']","{'cloud': ['bigquery'], 'databases': ['elastic...",12
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None,12
411096,Data Scientist,Data Scientist Specialist,Argentina,via LinkedIn,Full-time,False,Argentina,2023-12-31,False,False,Argentina,None,NaN,NaN,ICBC Argentina,"['python', 'sql', 'nosql', 'gcp', 'aws', 'azur...","{'analyst_tools': ['power bi'], 'cloud': ['gcp...",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12
103131,Data Analyst,Principal data analyst,"Dallas, TX",via Talent.com,Full-time,False,"Texas, United States",2023-12-31,True,False,United States,None,NaN,NaN,Metro,None,None,12

In [86]:
# lets check for data analyst only
df[df['job_title_short']=='Data Analyst']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
364349,Data Analyst,Functional analyst Adobe Analytics,"Madrid, Spain",via Recruit.net,Full-time,False,Spain,2023-01-01,False,False,Spain,None,NaN,NaN,Krell Consulting & Training,"['html', 'css', 'javascript', 'sql']","{'programming': ['html', 'css', 'javascript', ...",1
732186,Data Analyst,Data & Analytics Analyst,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-01,True,False,Poland,None,NaN,NaN,NatWest Polska,['tableau'],{'analyst_tools': ['tableau']},1
346874,Data Analyst,Technical Business/ Data Analyst,"Philadelphia, PA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01,False,False,United States,None,NaN,NaN,Diverse Lynx,"['python', 'sql', 'shell', 'unix']","{'os': ['unix'], 'programming': ['python', 'sq...",1
404115,Data Analyst,Data Analyst - Onsite,"Dallas, TX",via Indeed,Full-time,False,"Texas, United States",2023-01-01,False,True,United States,None,NaN,NaN,I.E.S.,"['sql', 'azure', 'snowflake', 'excel', 'power ...","{'analyst_tools': ['excel', 'power bi', 'table...",1
188178,Data Analyst,Data Analyst,"Madrid, Spain",via LinkedIn,Full-time,False,Spain,2023-01-01,True,False,Spain,None,NaN,NaN,SDG Group España,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94222,Data Analyst,Data Analyst III,"Sunnyvale, CA",via Monster,Full-time,False,"California, United States",2023-12-31,False,True,United States,None,NaN,NaN,Wal-Mart,None,None,12
728684,Data Analyst,Data Analyst- Payroll,"Modena, Province of Modena, Italy",via BeBee,Full-time,False,Italy,2023-12-31,False,False,Italy,None,NaN,NaN,Codemotion,"['t-sql', 'sql']","{'programming': ['t-sql', 'sql']}",12
392000,Data Analyst,Data Analyst,Singapore,via BeBee Singapore,Contractor,False,Singapore,2023-12-31,False,False,Singapore,None,NaN,NaN,PERSOLKELLY Singapore Pte Ltd (Formerly Kelly ...,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12
103131,Data Analyst,Principal data analyst,"Dallas, TX",via Talent.com,Full-time,False,"Texas, United States",2023-12-31,True,False,United States,None,NaN,NaN,Metro,None,None,12

In [89]:
# now i want to remove empty values from salary_year_avg column
df_delete_empty = df.dropna(subset=['salary_year_avg'],inplace=False)
df_delete_empty

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
776813,Senior Data Scientist,Senior Data Scientist,"Austin, TX",via Indeed,Full-time,False,Sudan,2023-01-01,False,True,Sudan,year,145000.0,NaN,CyberCoders,"['python', 'azure', 'pytorch', 'tensorflow', '...","{'analyst_tools': ['datarobot'], 'cloud': ['az...",1
777985,Data Engineer,"Data Engineer - Spark, Scala, Kafka, Flink","San Jose, CA",via Indeed,Full-time,False,Sudan,2023-01-01,True,False,Sudan,year,175000.0,NaN,CyberCoders,"['scala', 'java', 'aws', 'spark', 'kafka', 'ha...","{'cloud': ['aws'], 'libraries': ['spark', 'kaf...",1
69156,Data Scientist,Staff Data Scientist,Anywhere,via Indeed,Full-time,True,"California, United States",2023-01-01,False,True,United States,year,202500.0,NaN,CyberCoders,"['python', 'java', 'scala', 'sql', 'aws', 'had...","{'cloud': ['aws'], 'libraries': ['hadoop', 'sp...",1
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01,True,False,Argentina,year,65000.0,NaN,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",1
2862,Data Scientist,Marketing Data Scientist,Anywhere,via Indeed,Contractor,True,Georgia,2023-01-01,False,False,United States,year,113000.0,NaN,"Stefanini, Inc","['python', 'r', 'azure', 'databricks', 'aws', ...","{'analyst_tools': ['tableau', 'power bi'], 'cl...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714269,Data Scientist,Data Science Lead,Cyprus,via Ai-Jobs.net,Full-time,False,Cyprus,2023-12-31,False,False,Cyprus,year,191000.0,NaN,Palta,['python'],{'programming': ['python']},12
22280,Senior Data Analyst,"Lead Data Analyst/Senior Data Analyst, Tiktok ...","New York, NY",via LinkedIn,Full-time,False,"New York, United States",2023-12-31,False,True,United States,year,172118.5,NaN,TikTok,"['sql', 'php', 'python', 'perl', 'express', 't...","{'analyst_tools': ['tableau'], 'programming': ...",12
250599,Data Analyst,Supply Chain Analytics Manager,Anywhere,via Get.It,Full-time,True,"California, United States",2023-12-31,False,True,United States,year,83000.0,NaN,Get It Recruit - Transportation,None,None,12
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31,False,True,Sudan,year,162500.0,NaN,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12

In [88]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
461362,Data Scientist,Turing Hiring Near Me – Remote Data Scientist ...,"Palo Alto, CA",via Jobs Picks,Full-time,False,"California, United States",2023-01-01,False,False,United States,None,NaN,NaN,Turing,"['python', 'tensorflow', 'keras', 'pandas', 'n...","{'libraries': ['tensorflow', 'keras', 'pandas'...",1
274144,Data Scientist,STAGE - Assistant(e) Data Scientist – Quantum ...,"Montrouge, France",via BeBee,Internship,False,France,2023-01-01,False,False,France,None,NaN,NaN,Crédit Agricole S.A.,None,None,1
364349,Data Analyst,Functional analyst Adobe Analytics,"Madrid, Spain",via Recruit.net,Full-time,False,Spain,2023-01-01,False,False,Spain,None,NaN,NaN,Krell Consulting & Training,"['html', 'css', 'javascript', 'sql']","{'programming': ['html', 'css', 'javascript', ...",1
364347,Senior Data Engineer,Senior Data Engineer (Innovation Insurer),Hong Kong,via Jobs In Hong Kong,Full-time,False,Hong Kong,2023-01-01,False,False,Hong Kong,None,NaN,NaN,MatchTalent Limited,"['sql', 'mongodb', 'mongodb', 'r', 'python', '...","{'analyst_tools': ['alteryx', 'tableau', 'qlik...",1
346928,Cloud Engineer,"Data Center Storage with Avamar/Sacramento, CA...","Sacramento, CA",via LinkedIn,Contractor,False,"California, United States",2023-01-01,True,False,United States,None,NaN,NaN,Suncap Technology,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61924,Machine Learning Engineer,Senior/Staff MLOps Engineer,"Denver, CO",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,EvenUp,"['elasticsearch', 'bigquery']","{'cloud': ['bigquery'], 'databases': ['elastic...",12
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None,12
411096,Data Scientist,Data Scientist Specialist,Argentina,via LinkedIn,Full-time,False,Argentina,2023-12-31,False,False,Argentina,None,NaN,NaN,ICBC Argentina,"['python', 'sql', 'nosql', 'gcp', 'aws', 'azur...","{'analyst_tools': ['power bi'], 'cloud': ['gcp...",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12
103131,Data Analyst,Principal data analyst,"Dallas, TX",via Talent.com,Full-time,False,"Texas, United States",2023-12-31,True,False,United States,None,NaN,NaN,Metro,None,None,12

In [90]:
# Filter the dataframe to exclude 'Contractor' jobs
df_no_contractor = df_delete_empty[df_delete_empty['job_schedule_type'] != 'Contractor']

# Display the result to verify
df_no_contractor

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
776813,Senior Data Scientist,Senior Data Scientist,"Austin, TX",via Indeed,Full-time,False,Sudan,2023-01-01,False,True,Sudan,year,145000.0,NaN,CyberCoders,"['python', 'azure', 'pytorch', 'tensorflow', '...","{'analyst_tools': ['datarobot'], 'cloud': ['az...",1
777985,Data Engineer,"Data Engineer - Spark, Scala, Kafka, Flink","San Jose, CA",via Indeed,Full-time,False,Sudan,2023-01-01,True,False,Sudan,year,175000.0,NaN,CyberCoders,"['scala', 'java', 'aws', 'spark', 'kafka', 'ha...","{'cloud': ['aws'], 'libraries': ['spark', 'kaf...",1
69156,Data Scientist,Staff Data Scientist,Anywhere,via Indeed,Full-time,True,"California, United States",2023-01-01,False,True,United States,year,202500.0,NaN,CyberCoders,"['python', 'java', 'scala', 'sql', 'aws', 'had...","{'cloud': ['aws'], 'libraries': ['hadoop', 'sp...",1
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01,True,False,Argentina,year,65000.0,NaN,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",1
705374,Data Scientist,Data Science Manager,"Carnegie, PA",via Indeed,Full-time,False,Georgia,2023-01-01,False,True,United States,year,133500.0,NaN,VISIMO,"['python', 'numpy', 'pandas', 'scikit-learn', ...","{'libraries': ['numpy', 'pandas', 'scikit-lear...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714269,Data Scientist,Data Science Lead,Cyprus,via Ai-Jobs.net,Full-time,False,Cyprus,2023-12-31,False,False,Cyprus,year,191000.0,NaN,Palta,['python'],{'programming': ['python']},12
22280,Senior Data Analyst,"Lead Data Analyst/Senior Data Analyst, Tiktok ...","New York, NY",via LinkedIn,Full-time,False,"New York, United States",2023-12-31,False,True,United States,year,172118.5,NaN,TikTok,"['sql', 'php', 'python', 'perl', 'express', 't...","{'analyst_tools': ['tableau'], 'programming': ...",12
250599,Data Analyst,Supply Chain Analytics Manager,Anywhere,via Get.It,Full-time,True,"California, United States",2023-12-31,False,True,United States,year,83000.0,NaN,Get It Recruit - Transportation,None,None,12
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31,False,True,Sudan,year,162500.0,NaN,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12

In [91]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
461362,Data Scientist,Turing Hiring Near Me – Remote Data Scientist ...,"Palo Alto, CA",via Jobs Picks,Full-time,False,"California, United States",2023-01-01,False,False,United States,None,NaN,NaN,Turing,"['python', 'tensorflow', 'keras', 'pandas', 'n...","{'libraries': ['tensorflow', 'keras', 'pandas'...",1
274144,Data Scientist,STAGE - Assistant(e) Data Scientist – Quantum ...,"Montrouge, France",via BeBee,Internship,False,France,2023-01-01,False,False,France,None,NaN,NaN,Crédit Agricole S.A.,None,None,1
364349,Data Analyst,Functional analyst Adobe Analytics,"Madrid, Spain",via Recruit.net,Full-time,False,Spain,2023-01-01,False,False,Spain,None,NaN,NaN,Krell Consulting & Training,"['html', 'css', 'javascript', 'sql']","{'programming': ['html', 'css', 'javascript', ...",1
364347,Senior Data Engineer,Senior Data Engineer (Innovation Insurer),Hong Kong,via Jobs In Hong Kong,Full-time,False,Hong Kong,2023-01-01,False,False,Hong Kong,None,NaN,NaN,MatchTalent Limited,"['sql', 'mongodb', 'mongodb', 'r', 'python', '...","{'analyst_tools': ['alteryx', 'tableau', 'qlik...",1
346928,Cloud Engineer,"Data Center Storage with Avamar/Sacramento, CA...","Sacramento, CA",via LinkedIn,Contractor,False,"California, United States",2023-01-01,True,False,United States,None,NaN,NaN,Suncap Technology,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61924,Machine Learning Engineer,Senior/Staff MLOps Engineer,"Denver, CO",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,EvenUp,"['elasticsearch', 'bigquery']","{'cloud': ['bigquery'], 'databases': ['elastic...",12
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None,12
411096,Data Scientist,Data Scientist Specialist,Argentina,via LinkedIn,Full-time,False,Argentina,2023-12-31,False,False,Argentina,None,NaN,NaN,ICBC Argentina,"['python', 'sql', 'nosql', 'gcp', 'aws', 'azur...","{'analyst_tools': ['power bi'], 'cloud': ['gcp...",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12
103131,Data Analyst,Principal data analyst,"Dallas, TX",via Talent.com,Full-time,False,"Texas, United States",2023-12-31,True,False,United States,None,NaN,NaN,Metro,None,None,12

In [92]:
# Delete the row with index 702239
df.drop(index=702239, inplace=False)

# Verify it's gone by checking the last few rows where it was previously visible
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,month_number
61924,Machine Learning Engineer,Senior/Staff MLOps Engineer,"Denver, CO",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,EvenUp,"['elasticsearch', 'bigquery']","{'cloud': ['bigquery'], 'databases': ['elastic...",12
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None,12
411096,Data Scientist,Data Scientist Specialist,Argentina,via LinkedIn,Full-time,False,Argentina,2023-12-31,False,False,Argentina,None,NaN,NaN,ICBC Argentina,"['python', 'sql', 'nosql', 'gcp', 'aws', 'azur...","{'analyst_tools': ['power bi'], 'cloud': ['gcp...",12
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",12
103131,Data Analyst,Principal data analyst,"Dallas, TX",via Talent.com,Full-time,False,"Texas, United States",2023-12-31,True,False,United States,None,NaN,NaN,Metro,None,None,12