In [9]:
# so now we will try to get some more hands on grouping

In [10]:
# importing library
import pandas as pd
from datasets import load_dataset

In [11]:
# loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [13]:
# now data clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [18]:
# now we want to find jobs for specific country
df_india = df[df['job_country'] == 'India']
df_india.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,None,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,None,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,None,NaN,NaN,Exusia,None,None
38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,None,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,None,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."

In [19]:
# now we want to see the median salary for different job_title_short in india
df_india.groupby('job_title_short')['salary_year_avg'].mean()

job_title_short
Business Analyst              82255.125000
Cloud Engineer                         NaN
Data Analyst                  99149.925532
Data Engineer                123312.390533
Data Scientist               118203.690217
Machine Learning Engineer    111372.570175
Senior Data Analyst          105740.592593
Senior Data Engineer         132148.631579
Senior Data Scientist        126035.787879
Software Engineer             78420.377778
Name: salary_year_avg, dtype: float64

In [20]:
# suppose we want other stats as well
df_india.groupby('job_title_short')['salary_year_avg'].agg(['mean', 'median', 'min', 'max'])

                                    mean    median      min       max
job_title_short
Business Analyst            82255.125000   64800.0  43200.0  142025.0
Cloud Engineer                       NaN       NaN      NaN       NaN
Data Analyst                99149.925532  100500.0  32400.0  650000.0
Data Engineer              123312.390533  147500.0  43200.0  249000.0
Data Scientist             118203.690217  114008.0  43200.0  204381.0
Machine Learning Engineer  111372.570175   79200.0  32500.0  267000.0
Senior Data Analyst        105740.592593  111175.0  64800.0  177283.0
Senior Data Engineer       132148.631579  147500.0  35000.0  181765.0
Senior Data Scientist      126035.787879  149653.0  64800.0  170575.0
Software Engineer           78420.377778   79200.0  44418.5  200000.0

In [22]:
# now supoose we want to sort values by median in desc order
df_india.groupby('job_title_short')['salary_year_avg'].agg(['median', 'mean', 'min', 'max']).sort_values('median', ascending=False)

                             median           mean      min       max
job_title_short
Senior Data Scientist      149653.0  126035.787879  64800.0  170575.0
Senior Data Engineer       147500.0  132148.631579  35000.0  181765.0
Data Engineer              147500.0  123312.390533  43200.0  249000.0
Data Scientist             114008.0  118203.690217  43200.0  204381.0
Senior Data Analyst        111175.0  105740.592593  64800.0  177283.0
Data Analyst               100500.0   99149.925532  32400.0  650000.0
Machine Learning Engineer   79200.0  111372.570175  32500.0  267000.0
Software Engineer           79200.0   78420.377778  44418.5  200000.0
Business Analyst            64800.0   82255.125000  43200.0  142025.0
Cloud Engineer                  NaN            NaN      NaN       NaN