In [3]:
# importing libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

In [4]:
# loading datset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [5]:
# sorting by date
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
df_cleaned = df.dropna(how='all')

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
# looking for specific columns
df_cleaned.iloc[:9,11:14]

  salary_rate  salary_year_avg  salary_hour_avg
0        None              NaN              NaN
1        None              NaN              NaN
2        None              NaN              NaN
3        None              NaN              NaN
4        None              NaN              NaN
5        None              NaN              NaN
6        None              NaN              NaN
7        None              NaN              NaN
8        None              NaN              NaN

In [ ]:
# now we will fill those values with '0'
df_fill = df_cleaned.fillna(0)

# now seeing the result
df_fill.iloc[:9,11:14]

  salary_rate  salary_year_avg  salary_hour_avg
0           0              0.0              0.0
1           0              0.0              0.0
2           0              0.0              0.0
3           0              0.0              0.0
4           0              0.0              0.0
5           0              0.0              0.0
6           0              0.0              0.0
7           0              0.0              0.0
8           0              0.0              0.0

In [34]:
# now we have to delete duplicate rows
df_unique = df_fill.drop_duplicates()

# checking the info
df_unique.info()

# we can see rows value is reduced from 785741 to 785640 
reduced_rows = 785741 - 785640
reduced_rows

<class 'pandas.core.frame.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  object
 1   job_title              785640 non-null  object
 2   job_location           785640 non-null  object
 3   job_via                785640 non-null  object
 4   job_schedule_type      785640 non-null  object
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  object
 7   job_posted_date        785640 non-null  datetime64[ns]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785640 non-null  object
 11  salary_rate            785640 non-null  object
 12  salary_year_avg        785640 non-null  float64
 13  salary_hour_avg        785640 non-null  float64
 14  company_name           785640 non-null  object
 15  job_skills             785640 non-null  object
 16  job_type_skills        785640 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

101

In [36]:
# now if we try to remove certain job title because sometime same job is posted more than once
df_job_title_unique = df_fill.drop_duplicates(subset='job_title')

# now lets check unique job titles
df_job_title_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234674 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        234674 non-null  object
 1   job_title              234674 non-null  object
 2   job_location           234674 non-null  object
 3   job_via                234674 non-null  object
 4   job_schedule_type      234674 non-null  object
 5   job_work_from_home     234674 non-null  bool
 6   search_location        234674 non-null  object
 7   job_posted_date        234674 non-null  datetime64[ns]
 8   job_no_degree_mention  234674 non-null  bool
 9   job_health_insurance   234674 non-null  bool
 10  job_country            234674 non-null  object
 11  salary_rate            234674 non-null  object
 12  salary_year_avg        234674 non-null  float64
 13  salary_hour_avg        234674 non-null  float64
 14  company_name           234674 non-null  object
 15  job_skills             234674 non-null  object
 16  job_type_skills        234674 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 27.5+ MB